import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className flex flex-col`}>
        <div className="sticky top-0 shadow-md">
          <Header />
        </div>
        <div className="flex h-[94vh]">
          <div className="lg:w-[20%]  overflow-y-scroll">
            <Sidebar />
          </div>
          <div className="lg:w-[80%] overflow-y-scroll">{children}</div>
        </div>
      </body>
    </html>
  );
}
